number = 7

[play_positions]
attack  = "J25"
defence = "J9"

[set_piece_positions]
"kick off own"                = "K23"
"kick off opp"                = "K13"
"goal kick own"               = "K27"
"goal kick opp"               = "K13"
"corner own left"             = "K7"
"corner own right"            = "K7"
"corner opp left"             = "K27"
"corner opp right"            = "K27"
"throw in own left own half"  = "K13"
"throw in own left opp half"  = "K13"
"throw in own right own half" = "K13"
"throw in own right opp half" = "K13"
"throw in opp left own half"  = "K13"
"throw in opp left opp half"  = "K13"
"throw in opp right own half" = "K13"
"throw in opp right opp half" = "K13"
