number = 1

[play_positions]
attack  = "N9"
defence = "N1"

[set_piece_positions]
"kick off own"                = "N3"
"kick off opp"                = "N3"
"goal kick own"               = "on_ball"
"goal kick opp"               = "N5"
"corner own left"             = "N34"
"corner own right"            = "N34"
"corner opp left"             = "N3"
"corner opp right"            = "N3"
"throw in own left own half"  = "N3"
"throw in own left opp half"  = "N3"
"throw in own right own half" = "N3"
"throw in own right opp half" = "N3"
"throw in opp left own half"  = "N3"
"throw in opp left opp half"  = "N3"
"throw in opp right own half" = "N3"
"throw in opp right opp half" = "N3"
