number = 10

[play_positions]
attack  = "N35"
defence = "N15"

[set_piece_positions]
"kick off own"                = "on_ball"
"kick off opp"                = "N18"
"goal kick own"               = "N20"
"goal kick opp"               = "N20"
"corner own left"             = "N34"
"corner own right"            = "N34"
"corner opp left"             = "N13"
"corner opp right"            = "N13"
"throw in own left own half"  = "N18"
"throw in own left opp half"  = "N18"
"throw in own right own half" = "N18"
"throw in own right opp half" = "N18"
"throw in opp left own half"  = "N18"
"throw in opp left opp half"  = "N18"
"throw in opp right own half" = "N18"
"throw in opp right opp half" = "N18"
