# Стартовая позиция: центр поля по X, 10м к своей половине от центра (строка 16)
# Атака: левый фланг у ворот B (колонка E=5, строки 35-40)
# Защита: совпадает со стартовой

number = 1
start_position   = "N16"
attack_position  = "E35"
defence_position = "N16"
