number = 2

[play_positions]
attack  = "K16"
defence = "K16"

[set_piece_positions]
"kick off own"                  = "K16"
"kick off opp"                  = "K16"
"goal kick own"                 = "K30"
"goal kick opp"                 = "K16"
"corner own left"               = "K16"
"corner own right"              = "K16"
"corner opp left"               = "K16"
"corner opp right"              = "K16"
"throw in own left own half"    = "K16"
"throw in own left opp half"    = "K16"
"throw in own right own half"   = "K16"
"throw in own right opp half"   = "K16"
"throw in opp left own half"    = "K16"
"throw in opp left opp half"    = "K16"
"throw in opp right own half"   = "K16"
"throw in opp right opp half"   = "K16"
