number = 8

[play_positions]
attack  = "S25"
defence = "S9"

[set_piece_positions]
"kick off own"                = "S17"
"kick off opp"                = "S13"
"goal kick own"               = "S13"
"goal kick opp"               = "S27"
"corner own left"             = "S34"
"corner own right"            = "S34"
"corner opp left"             = "S13"
"corner opp right"            = "S13"
"throw in own left own half"  = "S13"
"throw in own left opp half"  = "S13"
"throw in own right own half" = "S13"
"throw in own right opp half" = "S13"
"throw in opp left own half"  = "S13"
"throw in opp left opp half"  = "S13"
"throw in opp right own half" = "S13"
"throw in opp right opp half" = "S13"
