number = 11

[play_positions]
attack  = "R35"
defence = "R15"

[set_piece_positions]
"kick off opp"                = "R18"
"kick off own"                = "R18"
"goal kick own"               = "R22"
"goal kick opp"               = "R10"
"corner own left"             = "R7"
"corner own right"            = "R7"
"corner opp left"             = "R30"
"corner opp right"            = "R30"
"throw in own left own half"  = "R18"
"throw in own left opp half"  = "R18"
"throw in own right own half" = "on_ball"
"throw in own right opp half" = "on_ball"
"throw in opp left own half"  = "R18"
"throw in opp left opp half"  = "R18"
"throw in opp right own half" = "R18"
"throw in opp right opp half" = "R18"
