number = 6

[play_positions]
attack  = "H25"
defence = "H9"

[set_piece_positions]
"kick off own"                = "H13"
"kick off opp"                = "H13"
"goal kick own"               = "H13"
"goal kick opp"               = "H27"
"corner own left"             = "H34"
"corner own right"            = "H34"
"corner opp left"             = "H13"
"corner opp right"            = "H13"
"throw in own left own half"  = "H13"
"throw in own left opp half"  = "H13"
"throw in own right own half" = "H13"
"throw in own right opp half" = "H13"
"throw in opp left own half"  = "H13"
"throw in opp left opp half"  = "H13"
"throw in opp right own half" = "H13"
"throw in opp right opp half" = "H13"
