number = 3

[play_positions]
attack  = "K18"
defence = "K5"

[set_piece_positions]
"kick off opp"                = "K7"
"kick off own"                = "K7"
"goal kick own"               = "K33"
"goal kick opp"               = "K15"
"corner own left"             = "K7"
"corner own right"            = "K7"
"corner opp left"             = "K35"
"corner opp right"            = "K35"
"throw in own left own half"  = "K33"
"throw in own left opp half"  = "K33"
"throw in own right own half" = "K33"
"throw in own right opp half" = "K33"
"throw in opp left own half"  = "K33"
"throw in opp left opp half"  = "K33"
"throw in opp right own half" = "K33"
"throw in opp right opp half" = "K33"
