number = 8

[play_positions]
attack  = "P25"
defence = "P9"

[set_piece_positions]
"kick off opp"                = "N13"
"kick off own"                = "N13"
"goal kick own"               = "N27"
"goal kick opp"               = "N13"
"corner own left"             = "N7"
"corner own right"            = "N7"
"corner opp left"             = "N27"
"corner opp right"            = "N13"
"throw in own left own half"  = "N13"
"throw in own left opp half"  = "N13"
"throw in own right own half" = "N13"
"throw in own right opp half" = "N13"
"throw in opp left own half"  = "N13"
"throw in opp left opp half"  = "N13"
"throw in opp right own half" = "N13"
"throw in opp right opp half" = "N13"
