number = 1

[play_positions]
attack  = "N16"
defence = "N16"

[set_piece_positions]
"kick off own"                  = "on_ball"
"kick off opp"                  = "N16"
"goal kick own"                 = "on_ball"
"goal kick opp"                 = "N25"
"corner own left"               = "on_ball"
"corner own right"              = "on_ball"
"corner opp left"               = "N16"
"corner opp right"              = "N16"
"throw in own left own half"    = "on_ball"
"throw in own left opp half"    = "on_ball"
"throw in own right own half"   = "on_ball"
"throw in own right opp half"   = "on_ball"
"throw in opp left own half"    = "N16"
"throw in opp left opp half"    = "N16"
"throw in opp right own half"   = "N16"
"throw in opp right opp half"   = "N16"
