number = 9

[play_positions]
attack  = "G34"
defence = "G15"

[set_piece_positions]
"kick off own"                = "G18"
"kick off opp"                = "G18"
"goal kick own"               = "G18"
"goal kick opp"               = "G30"
"corner own left"             = "G34"
"corner own right"            = "G34"
"corner opp left"             = "G10"
"corner opp right"            = "G10"
"throw in own left own half"  = "on_ball"
"throw in own left opp half"  = "on_ball"
"throw in own right own half" = "G18"
"throw in own right opp half" = "G18"
"throw in opp left own half"  = "G18"
"throw in opp left opp half"  = "G18"
"throw in opp right own half" = "G18"
"throw in opp right opp half" = "G18"
