number = 11

[play_positions]
attack  = "T34"
defence = "T15"

[set_piece_positions]
"kick off own"                = "T18"
"kick off opp"                = "T18"
"goal kick own"               = "T18"
"goal kick opp"               = "T30"
"corner own left"             = "T34"
"corner own right"            = "T34"
"corner opp left"             = "T10"
"corner opp right"            = "T10"
"throw in own left own half"  = "T18"
"throw in own left opp half"  = "T18"
"throw in own right own half" = "on_ball"
"throw in own right opp half" = "on_ball"
"throw in opp left own half"  = "T18"
"throw in opp left opp half"  = "T18"
"throw in opp right own half" = "T18"
"throw in opp right opp half" = "T18"
