number = 10

[play_positions]
attack  = "I35"
defence = "I15"

[set_piece_positions]
"kick off"                  = "on_ball"
"throw in own left own half"  = "I18"
"throw in own left opp half"  = "I18"
"throw in own right own half" = "I18"
"throw in own right opp half" = "I18"
"throw in opp left own half"  = "I18"
"throw in opp left opp half"  = "I18"
"throw in opp right own half" = "I18"
"throw in opp right opp half" = "I18"
