number = 5

[play_positions]
attack  = "T18"
defence = "T5"

[set_piece_positions]
"kick off"                  = "T7"
"throw in own left own half"  = "T7"
"throw in own left opp half"  = "T7"
"throw in own right own half" = "T7"
"throw in own right opp half" = "T7"
"throw in opp left own half"  = "T7"
"throw in opp left opp half"  = "T7"
"throw in opp right own half" = "T7"
"throw in opp right opp half" = "T7"
