number = 6

[play_positions]
attack  = "F25"
defence = "F9"

[set_piece_positions]
"kick off opp"                = "F13"
"kick off own"                = "F13"
"goal kick own"               = "F33"
"goal kick opp"               = "F13"
"corner own left"             = "F7"
"corner own right"            = "F7"
"corner opp left"             = "F13"
"corner opp right"            = "F27"
"throw in own left own half"  = "F13"
"throw in own left opp half"  = "F13"
"throw in own right own half" = "F13"
"throw in own right opp half" = "F13"
"throw in opp left own half"  = "F13"
"throw in opp left opp half"  = "F13"
"throw in opp right own half" = "F13"
"throw in opp right opp half" = "F13"
