number = 9

[play_positions]
attack  = "T25"
defence = "T9"

[set_piece_positions]
"kick off own"                = "T23"
"kick off opp"                = "T13"
"goal kick own"               = "T22"
"goal kick opp"               = "T10"
"corner own left"             = "T7"
"corner own right"            = "T7"
"corner opp left"             = "T30"
"corner opp right"            = "T30"
"throw in own left own half"  = "on_ball"
"throw in own left opp half"  = "on_ball"
"throw in own right own half" = "T13"
"throw in own right opp half" = "T13"
"throw in opp left own half"  = "T13"
"throw in opp left opp half"  = "T13"
"throw in opp right own half" = "T13"
"throw in opp right opp half" = "T13"
