number = 5

[play_positions]
attack  = "T18"
defence = "T5"

[set_piece_positions]
"kick off own"                = "T7"
"kick off opp"                = "T7"
"goal kick own"               = "T7"
"goal kick opp"               = "T25"
"corner own left"             = "T34"
"corner own right"            = "on_ball"
"corner opp left"             = "T5"
"corner opp right"            = "T5"
"throw in own left own half"  = "T7"
"throw in own left opp half"  = "T7"
"throw in own right own half" = "T7"
"throw in own right opp half" = "T7"
"throw in opp left own half"  = "T7"
"throw in opp left opp half"  = "T7"
"throw in opp right own half" = "T7"
"throw in opp right opp half" = "T7"
